apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pod-pv
spec:
  storageClassName: localdisk
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /tmp/k8s
