apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-v1
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume-v1
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-config-volume-v1
          configMap:
            name: nginx-configmap-v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-v2
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume-v2
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-config-volume-v2
          configMap:
            name: nginx-configmap-v2
