apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap-v1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Welcome to Nginx!</title>
      </head>
      <body>
        <p>This is Deployment One</p>
      </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap-v2
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Welcome to Nginx!</title>
      </head>
      <body>
        <p>This is Deployment Two</p>
      </body>
    </html>
